version: '3'

volumes:
  esdata:
  mongo-data:
networks:
  elk-network:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      elk-network:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.4.2
    ports:
      - "5601:5601"
    networks:
      elk-network:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.4.2
    depends_on:
    - elasticsearch
    networks:
      elk-network:
    ports:
    - "5044:5044"
    - "28777:28777"
    volumes:
    - ./config-dir/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    - ./etc/logstash/pipeline:/usr/share/logstash/pipeline:ro
    command: logstash -f /etc/logstash/conf.d/logstash.conf
